spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: studentsapi

kafka:
  topic:
    name: ${TOPIC:students_notes}

rest:
  students-producer:
    url-prefix: /api/v1
    uri:
      send-msg-for-avg-notes: /students/messages/average-notes
