spring:
  application:
    name: studentsapi
  kafka:
    consumer:
      group-id: student-notes-group-id
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8001/realms/studentsapi-realm}

aws:
  region: ${REGION:DUMMYREGION}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}
    accesskey: ${DYNAMODB_ACCESS_KEY:DUMMYIDEXAMPLE}
    secretkey: ${DYNAMODB_SECRET_KEY:DUMMYIDEXAMPLE}

rest:
  students-producer:
    url-base: ${STUDENTS_PRODUCER_URL_BASE:http://localhost:8888}

springdoc:
  swagger-ui:
    path: /swagger-students.html

logging:
  level:
    org.apache.hc.client5.http: DEBUG
    root: INFO
    "[org.springframework.web]": DEBUG
    "[org.springframework.kafka]": INFO
    "[com.ppalma.studentsapi]": DEBUG

