spring:
  application:
    name: studentsapi
  kafka:
    consumer:
      group-id: student-notes-group-id
    bootstrap-servers: ${KAFKA_HOST:localhost:29092}

aws:
  region: ${REGION:us-west-2}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}
    accesskey: ${DYNAMODB_ACCESS_KEY:DUMMYIDEXAMPLE}
    secretkey: ${DYNAMODB_SECRET_KEY:DUMMYIDEXAMPLE}

kafka:
  topic:
    name: ${TOPIC:students_notes}

rest:
  students-producer:
    url-base: ${STUDENT_NOTES_URL_BASE:http://localhost:8888}
    url-prefix: /api/v1
    uri:
      send-msg-for-avg-notes: /students/messages/average-notes

springdoc:
  swagger-ui:
    path: /swagger-students.html

logging:
  level:
    org.apache.hc.client5.http: DEBUG
