spring:
  application:
    name: studentsapi
  kafka:
    consumer:
      group-id: student-notes-group-id
    bootstrap-servers: ${KAFKA_HOST:localhost:29092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8001/realms/studentsapi-realm}

aws:
  region: ${REGION:DUMMYREGION}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}
    accesskey: ${DYNAMODB_ACCESS_KEY:DUMMYIDEXAMPLE}
    secretkey: ${DYNAMODB_SECRET_KEY:DUMMYIDEXAMPLE}

rest:
  students-producer:
    url-base: ${STUDENTS_PRODUCER_URL_BASE:http://localhost:8888}