spring:
  application:
    name: studentsapi
  kafka:
    consumer:
      group-id: student-notes-group-id
    bootstrap-servers: ${KAFKA_HOST}

aws:
  region: ${REGION}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT}
    accesskey: ${DYNAMODB_ACCESS_KEY}
    secretkey: ${DYNAMODB_SECRET_KEY}

rest:
  students-producer:
    url-base: ${STUDENTS_PRODUCER_URL_BASE}

springdoc:
  swagger-ui:
    path: /swagger-students.html

logging:
  level:
    org.apache.hc.client5.http: DEBUG
    root: INFO
    "[org.springframework.web]": DEBUG
    "[org.springframework.kafka]": INFO
    "[com.ppalma.studentsapi]": DEBUG

