spring:
  application:
    name: studentsapi
  kafka:
    consumer:
      group-id: student-notes-group-id
    bootstrap-servers: ${KAFKA_HOST:localhost:29092}

amazon:
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}
  aws:
    accesskey: ${DYNAMODB_ACCESS_KEY:DUMMYIDEXAMPLE}
    secretkey: ${DYNAMODB_SECRET_KEY:DUMMYIDEXAMPLE}

kafka:
  topic:
    name: ${TOPIC:students_notes}

rest:
  endpoint:
    students-notes:
      url-base: ${STUDENT_NOTES_URL_BASE:http://localhost:8888}
      url-prefix: /api/v1
      send-msg-for-avg-notes: /students/messages/avg-notes

springdoc:
  swagger-ui:
    path: /swagger-students.html

logging:
  level:
    org.apache.hc.client5.http: DEBUG
