package com.ppalma.studentsapi.infrastructure.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "student")
public class StudentEntity {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute
  private String dni;

  @DynamoDBAttribute
  private String name;

  @DynamoDBAttribute
  private List<Double> notes;

  @DynamoDBAttribute
  private Double averageNotes;
}
