version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:22888:23888

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_INTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      KAFKA_JVM_PERFORMANCE_OPTS: "-Xmx256m -Xms256m"

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: "/"
      KAFKA_BROKERCONNECT: kafka:19092

  studentsapi:
    image: pedroapalma/studentsapi:latest
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "80:8080"
    environment:
      VAULT_HOST: '10.0.30.106'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'

  kafkaproducer:
    image: pedroapalma/kafkaproducer:latest
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8888:8888"
    environment:
      VAULT_HOST: '10.0.30.106'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'